name: Build, Publish, Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # On semantic tag push
      
jobs:
  publish:
    name: Build Distribution
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing and sigstore
      contents: write  # IMPORTANT: mandatory for making GitHub Releases

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: pip
        
    - name: Install build
      run: >-
        python3 -m
        pip install
        build
        --user
        
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
      
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
          
    - name: Create GitHub Release Draft
      # Create and upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create --draft
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --generate-notes
        dist/**
        
